### ISSUE TITLE
Feedback on Mask2Former baseline code

### ISSUE THREAD

**Issue by RGring** [PRBonn/phenobench-baselines#1]
Hi,
Thanks a lot for providing all these baselines, weights and masks. I am really impressed by the structured repositories regarding the phenobench dataset.

I just wanted to give some feedback on running the Mask2Former baseline code.
Instruction on how to convert the data in the format expected by Detectron2 is missing.
- src/data_preprocessing/prepare_dataset_plants.py
- src/data_preprocessing/prepare_dataset_leaves.py
- src/data_preprocessing/prepare_coco_semantic_annos_from_panoptic_annos.py (note, that plants are commented out)

Note, that by default the folders and *.json files are named {plants/leaves}\_panoptic_{train/val}. However, in Mask2Former you use phenorob{plants/leaves}\_panoptic_{train/val}.

I suggest to add "make data" in the Makefile to make that process easy. 

Hope my input helps to resolve minor bugs!

**Comment by jbehley** [comment]
Thanks @RGring for the suggestions and for trying out the code, we will look into this and provide additional code to make it clearer.

As you might have noticed, the different baselines were implemented/run by different people and I pushed to get it out; maybe a little bit to rushed so that it's still a bit a "work-in-progress". hope that we can resolve all issues quickly.

**Comment by markselias** [comment]
Sorry for the delay, but we added the data preprocessing steps to the instructions now. Thanks for pointing it out @RGring !
